package com.ingg.exercise.sicbo.model.exception;

/**
 * <p>
 * Supertype of all checked exceptions generated by Sic Bo.
 * </p>
 *
 * @author iKernel Team
 * @author Inspired Gaming Group
 */
public abstract class SicBoException extends Exception {

    protected SicBoException() {
        super();
    }

}
